/* ============================================================
   data.js — Mock movie catalog data
   ============================================================
   
   Поле video:
   - VK Video: 'https://vk.com/video-XXXXXX_XXXXXX'
              или 'https://vkvideo.ru/video-XXXXXX_XXXXXX'
              или embed: 'https://vk.com/video_ext.php?oid=-XXX&id=XXX&hash=XXX'
   - null или отсутствует → заглушка "Скоро"
   ============================================================ */

const CINEMAX_DATA = {

  featured: [
    {
      id: 'interstellar',
      title: 'Интерстеллар',
      titleOrig: 'Interstellar',
      year: 2014, duration: '169 мин.', rating: 8.6,
      quality: '4K UHD', age: '16+',
      genres: ['Фантастика', 'Драма', 'Приключения'],
      director: 'Кристофер Нолан',
      cast: ['Мэттью МакКонахи', 'Энн Хэтэуэй', 'Джессика Честейн', 'Майкл Кейн'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Когда засуха приводит человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину в путешествие, чтобы превзойти прежние ограничения для космических путешествий человека.',
      poster: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&h=900&fit=crop',
      bg:     'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1800&fit=crop',
      video:  'https://vkvideo.ru/video-237370340_456239018', // ← вставьте реальную ссылку VK Video
      badge: null,
    },
    {
      id: 'dune',
      title: 'Дюна',
      titleOrig: 'Dune: Part One',
      year: 2021, duration: '155 мин.', rating: 8.0,
      quality: '4K UHD', age: '12+',
      genres: ['Фантастика', 'Эпик', 'Приключения'],
      director: 'Дени Вильнёв',
      cast: ['Тимоти Шаламе', 'Зендея', 'Оскар Айзек', 'Ребекка Фергюсон'],
      country: 'США, Канада',
      lang: 'Русский, Английский',
      desc: 'История Пола Атрейдеса — юноши, ставшего легендой. Он должен путешествовать на самую опасную планету во вселенной, чтобы обеспечить будущее своей семьи и своего народа.',
      poster: 'https://images.unsplash.com/photo-1543373014-cfe4f4bc1cdf?w=600&h=900&fit=crop',
      bg:     'https://images.unsplash.com/photo-1543373014-cfe4f4bc1cdf?w=1800&fit=crop',
      video:  null, // ← вставьте ссылку VK Video или оставьте null
      badge: 'hot',
    },
    {
      id: 'oppenheimer',
      title: 'Оппенгеймер',
      titleOrig: 'Oppenheimer',
      year: 2023, duration: '180 мин.', rating: 8.5,
      quality: '4K UHD', age: '18+',
      genres: ['Биография', 'Драма', 'История'],
      director: 'Кристофер Нолан',
      cast: ['Киллиан Мёрфи', 'Эмили Блант', 'Мэтт Деймон', 'Роберт Дауни мл.'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'История жизни американского физика Роберта Оппенгеймера, известного как отец атомной бомбы. Триумф и трагедия одного из самых сложных людей XX века.',
      poster: 'https://images.unsplash.com/photo-1532356884227-66d7c0e9e9f0?w=600&h=900&fit=crop',
      bg:     'https://images.unsplash.com/photo-1532356884227-66d7c0e9e9f0?w=1800&fit=crop',
      video:  null, // ← вставьте ссылку VK Video или оставьте null
      badge: 'new',
    },
  ],

  movies: [
    {
      id: 'gravity',
      title: 'Гравитация', titleOrig: 'Gravity',
      year: 2013, duration: '91 мин.', rating: 7.7,
      quality: '1080p', age: '12+',
      genres: ['Фантастика'],
      director: 'Альфонсо Куарон',
      cast: ['Сандра Буллок', 'Джордж Клуни'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Два астронавта оказываются одни в открытом космосе после того, как их шаттл был уничтожен. Им предстоит найти способ вернуться на Землю.',
      badge: 'hd',
      poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1800&fit=crop',
      video:  null, // ← вставьте ссылку VK Video
    },
    {
      id: 'arrival',
      title: 'Прибытие', titleOrig: 'Arrival',
      year: 2016, duration: '116 мин.', rating: 7.9,
      quality: '4K', age: '12+',
      genres: ['Фантастика', 'Драма'],
      director: 'Дени Вильнёв',
      cast: ['Эми Адамс', 'Джереми Реннер', 'Форест Уитакер'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Когда на Земле появляются загадочные инопланетные корабли, лингвист получает задание наладить коммуникацию с пришельцами, пока не началась война.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'martian',
      title: 'Марсианин', titleOrig: 'The Martian',
      year: 2015, duration: '144 мин.', rating: 8.0,
      quality: '4K', age: '12+',
      genres: ['Фантастика'],
      director: 'Ридли Скотт',
      cast: ['Мэтт Деймон', 'Джессика Честейн', 'Кристен Уиг'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Астронавт случайно остаётся в одиночестве на Марсе. Используя только имеющиеся ресурсы, он должен найти способ выжить и вернуться домой.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'inception',
      title: 'Начало', titleOrig: 'Inception',
      year: 2010, duration: '148 мин.', rating: 8.8,
      quality: '4K', age: '12+',
      genres: ['Фантастика', 'Триллер'],
      director: 'Кристофер Нолан',
      cast: ['Леонардо ДиКаприо', 'Джозеф Гордон-Левитт', 'Эллиот Пейдж', 'Том Харди'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Вор, специализирующийся на краже корпоративных секретов через технологию совместных сновидений, получает задачу имплантировать идею в сознание CEO.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'contact',
      title: 'Контакт', titleOrig: 'Contact',
      year: 1997, duration: '150 мин.', rating: 7.9,
      quality: '1080p', age: '6+',
      genres: ['Фантастика', 'Драма'],
      director: 'Роберт Земекис',
      cast: ['Джоди Фостер', 'Мэттью МакКонахи'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Учёный-астроном получает сигнал из другой звёздной системы с инструкцией по строительству машины для межзвёздных путешествий.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'bladerunner',
      title: 'Бегущий по лезвию 2049', titleOrig: 'Blade Runner 2049',
      year: 2017, duration: '164 мин.', rating: 8.0,
      quality: '4K', age: '18+',
      genres: ['Фантастика', 'Неонуар'],
      director: 'Дени Вильнёв',
      cast: ['Райан Гослинг', 'Харрисон Форд', 'Ана де Армас'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Офицер полиции Лос-Анджелеса обнаруживает секрет, который может погрузить общество в хаос. Он отправляется на поиски исчезнувшего репликанта.',
      badge: 'hd',
      poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'midsommar',
      title: 'Солнцестояние', titleOrig: 'Midsommar',
      year: 2019, duration: '148 мин.', rating: 7.1,
      quality: '4K', age: '18+',
      genres: ['Ужасы', 'Триллер'],
      director: 'Ари Астер',
      cast: ['Флоренс Пью', 'Джек Рейнор'],
      country: 'США, Швеция',
      lang: 'Русский, Английский',
      desc: 'Пара отправляется на шведский летний фестиваль, который проходит раз в 90 лет. Но праздник оборачивается кошмаром.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'hereditary',
      title: 'Реликвия', titleOrig: 'Hereditary',
      year: 2018, duration: '127 мин.', rating: 7.3,
      quality: '1080p', age: '18+',
      genres: ['Ужасы'],
      director: 'Ари Астер',
      cast: ['Тони Коллетт', 'Алекс Вулфф', 'Милли Шапиро'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'После смерти бабушки семья Грэм начинает вскрывать жуткие тайны своего прошлого. Потусторонние силы всё настойчивее дают о себе знать.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'tenet',
      title: 'Довод', titleOrig: 'Tenet',
      year: 2020, duration: '150 мин.', rating: 7.4,
      quality: '4K', age: '12+',
      genres: ['Боевик', 'Фантастика'],
      director: 'Кристофер Нолан',
      cast: ['Джон Дэвид Вашингтон', 'Роберт Паттинсон', 'Элизабет Дебики'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Агент спецслужб вооружён одним словом — «Довод». Он должен предотвратить Третью мировую войну, путешествуя сквозь перевёрнутый мир.',
      badge: 'hd',
      poster: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'parasite',
      title: 'Паразиты', titleOrig: 'Parasite',
      year: 2019, duration: '132 мин.', rating: 8.5,
      quality: '4K', age: '18+',
      genres: ['Триллер', 'Драма'],
      director: 'Пон Джун-хо',
      cast: ['Сон Кан-хо', 'Ли Сон-гюн', 'Чо Ё-джон'],
      country: 'Южная Корея',
      lang: 'Русский, Корейский',
      desc: 'Члены бедной семьи Ки-тек один за другим устраиваются на работу в богатую семью Пак. Постепенно жизни двух семей переплетаются.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1502136969935-8d8eef54d77b?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1502136969935-8d8eef54d77b?w=1800&fit=crop',
      video:  null,
    },
    {
      id: '1917',
      title: '1917', titleOrig: '1917',
      year: 2019, duration: '119 мин.', rating: 8.3,
      quality: '4K', age: '16+',
      genres: ['Военный', 'Драма'],
      director: 'Сэм Мендес',
      cast: ['Джордж МакКэй', 'Дин-Чарльз Чепмен'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Апрель 1917 года. Два британских солдата получают, казалось бы, невыполнимое задание — передать послание, которое может спасти жизни 1600 человек.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'whiplash',
      title: 'Одержимость', titleOrig: 'Whiplash',
      year: 2014, duration: '107 мин.', rating: 8.5,
      quality: '1080p', age: '16+',
      genres: ['Драма', 'Музыка'],
      director: 'Дэмьен Шазелл',
      cast: ['Майлз Теллер', 'Дж.К. Симмонс'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Молодой барабанщик поступает в престижную джазовую консерваторию, где попадает под крыло харизматичного, но жестокого преподавателя.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1800&fit=crop',
      video:  null,
    },
  ],

  series: [
    {
      id: 'bb',
      title: 'Во все тяжкие', titleOrig: 'Breaking Bad',
      year: 2008, seasons: 5, duration: '47 мин./эп.', rating: 9.5,
      quality: '4K', age: '18+',
      genres: ['Драма', 'Криминал'],
      director: 'Винс Гиллиган',
      cast: ['Брайан Крэнстон', 'Аарон Пол', 'Анна Ганн'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Учитель химии, которому поставили смертельный диагноз, начинает производить и продавать наркотики вместе со своим бывшим учеником.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'chernobyl',
      title: 'Чернобыль', titleOrig: 'Chernobyl',
      year: 2019, seasons: 1, duration: '60 мин./эп.', rating: 9.4,
      quality: '4K', age: '18+',
      genres: ['Мини-сериал', 'Драма'],
      director: 'Йохан Ренк',
      cast: ['Харрис Диккинсон', 'Джаред Харрис', 'Стеллан Скарсгорд'],
      country: 'США, Великобритания',
      lang: 'Русский, Английский',
      desc: 'Мини-сериал о катастрофе на Чернобыльской АЭС 1986 года и беспрецедентных усилиях советских людей по ликвидации её последствий.',
      badge: 'top',
      poster: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'got',
      title: 'Игра престолов', titleOrig: 'Game of Thrones',
      year: 2011, seasons: 8, duration: '57 мин./эп.', rating: 9.3,
      quality: '4K', age: '18+',
      genres: ['Фэнтези', 'Драма'],
      director: 'Дэвид Бениофф, Д.Б. Уайсс',
      cast: ['Эмилия Кларк', 'Кит Харингтон', 'Питер Динклэйдж', 'Лена Хиди'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Эпическая история борьбы за власть в огромном фэнтезийном мире. Несколько знатных семей сражаются за контроль над Железным троном.',
      badge: 'hd',
      poster: 'https://images.unsplash.com/photo-1488229297570-58520851e868?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1488229297570-58520851e868?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'peaky',
      title: 'Острые козырьки', titleOrig: 'Peaky Blinders',
      year: 2013, seasons: 6, duration: '60 мин./эп.', rating: 8.8,
      quality: '4K', age: '18+',
      genres: ['Криминал', 'Драма'],
      director: 'Стивен Найт',
      cast: ['Киллиан Мёрфи', 'Хелен МакКрори', 'Том Харди'],
      country: 'Великобритания',
      lang: 'Русский, Английский',
      desc: 'Британский гангстерский сериал о банде Острых козырьков из Бирмингема в начале XX века под руководством харизматичного Томми Шелби.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'witcher',
      title: 'Ведьмак', titleOrig: 'The Witcher',
      year: 2019, seasons: 3, duration: '60 мин./эп.', rating: 8.2,
      quality: '4K', age: '18+',
      genres: ['Фэнтези', 'Боевик'],
      director: 'Лорен Шмидт Хиссрих',
      cast: ['Генри Кавилл', 'Аня Чалотра', 'Фрейя Аллан'],
      country: 'США',
      lang: 'Русский, Английский',
      desc: 'Геральт из Ривии — мутировавший охотник на чудовищ — блуждает по миру. Его судьба переплетается с судьбами могущественной волшебницы и юной принцессы.',
      badge: 'new',
      poster: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1800&fit=crop',
      video:  null,
    },
    {
      id: 'dark',
      title: 'Тьма', titleOrig: 'Dark',
      year: 2017, seasons: 3, duration: '60 мин./эп.', rating: 8.8,
      quality: '4K', age: '16+',
      genres: ['Мистика', 'Фантастика'],
      director: 'Баран бо Одар',
      cast: ['Луис Хофманн', 'Оливер Маурер', 'Лиза Викари'],
      country: 'Германия',
      lang: 'Русский, Немецкий',
      desc: 'В маленьком немецком городке пропадают дети. Четыре семьи обнаруживают, что их прошлое, настоящее и будущее связаны мрачной тайной.',
      badge: null,
      poster: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=600&fit=crop',
      bg:     'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1800&fit=crop',
      video:  null,
    },
  ],

};
